### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by mendel3** [sheuronazxe/chatding#2]
I'm not sure how to get the active window in different OS's, but to play a sound cross platform, you can use the playsound library, found here:
https://pypi.org/project/playsound/
If you don't want to include any dependancies, you can play audio on mac with the command afplay, so you could use `os.system("afplay alert.wav")`

**Comment by sheuronazxe** [comment]
I would like to avoid dependencies so I included your solution. Thanks for the help.
